dependencies:
- python=3.6.2
- numpy=1.15.4
- scikit-learn=0.19.1
- matplotlib=3.0.2
- seaborn=0.9.0
- click=6.7
- coverage
- flake8
- pip=9.0
- pip:
    - black
    - jupyter
    - ipykernel
    - pandas-gbq==0.9.0
    - google-cloud==0.34.0
    - sanic==0.7.0
    - feather-format==0.4.0
    - pyyaml==3.12
    - psycopg2==2.7.3.2
    - nose==1.3.7
    - python-json-logger==0.1.8
    - google-api-python-client==1.6.2
    - pandas==0.23.4
    - pyarrow==0.10.0
    - python-dotenv>=0.5.1
    - statsmodels==0.8.0
    - statsd==3.3.0
    - xgboost==0.80
    - ipywidgets
    - plotly